config/routes.rb
Rails.application.routes.draw do
  root to: 'other_pages#index'

  get 'users/show' => 'users#show'

  resources :matters do
    resources :comments
    resource :favorites, only: %i[create destroy]
  end

  resources :informations, only: %i[create edit update destroy]

  resources :notifications, only: :index

  resources :conversations do
    resources :messages
  end

  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :matters, only: %i[index show edit update destroy]
    resources :labels
  end

  # ゲストユーザー機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/matter.rb
class Matter < ApplicationRecord
  validates :content, presence: true
  validates :user_id, presence: true

  enum priority: { 高: 0, 中: 1, 低: 2 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  # 通知機能
  has_many :notifications, dependent: :destroy
  # 画像アップロード
  has_many_attached :images
  # ラベル
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  # バッヂ処理（メール送信)
  def self.mail_check
    Matter.all.each do |matter|
      if matter.send_email == true
        matter.send_email = false
        matter.mail_status = 'メール送信済み'
        matter.save
        MatterMailer.matter_mail(matter).deliver
      end
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).present?
  end

  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and matter_id = ? and action = ? ', current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        matter_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(matter_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      matter_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
      notification.admin_checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/matters_controller.rb
class Admin::MattersController < ApplicationController
  before_action :if_not_admin
  before_action :set_matter, only: %i[show edit update destroy]

  def index
    @search = Matter.ransack(params[:q])
    @matters = @search.result
    @label = Label.new
    @labels = Label.all
  end

  def show; end

  def edit; end

  def update
    if @matter.update(matter_params)
      redirect_to admin_matters_path, notice: "#{@matter.title}を編集しました。"
    else
      flash[:alert] = '編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    @matter.destroy
    redirect_to admin_matters_path, notice: "#{@matter.title}を削除しました。"
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def matter_params
    params.require(:matter).permit(:content, :latitude, :longitude, :status, :priority, :start_time, :end_time, :remark, images: [])
  end

  def set_matter
    @matter = Matter.find(params[:id])
  end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :set_matter, only: %i[show edit update destroy]
  before_action :user_confirmation, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @search = Matter.ransack(params[:q])
    @matters = @search.result.page(params[:page])
    @matters = @matters.order(created_at: :desc)

    @informations = Information.all
    @information = Information.new
  end

  def show
    @favorite = current_user.favorites.find_by(matter_id: @matter.id)
    if @matter.latest_sender != current_user.name && (@matter.user_id == current_user.id || current_user.admin == true)
      @matter.latest_sender = nil
      @matter.save
    end
    @comments = @matter.comments
    @comment = @matter.comments.build
    current_user.admin? ? @notifications = Notification.where(matter_id: @matter.id) : @notifications = Notification.where(matter_id: @matter.id, visited_id: current_user)
    if @notifications.present?
      if current_user.admin?
        @notifications.each do |notification|
          notification.update_attributes(admin_checked: true)
        end
      else
        @notifications.each do |notification|
          notification.update_attributes(checked: true)
        end
      end
    end
  end

  def new
    @matter = Matter.new
  end

  def edit; end

  def create
    @matter = current_user.matters.build(matter_params)

    if @matter.save
      redirect_to @matter, notice: '案件を作成しました！'
    else
      render :new
    end
  end

  def update
    if @matter.update(matter_params)
      redirect_to @matter, notice: '案件を編集しました！'
    else
      render :edit
    end
  end

  def destroy
    @matter.destroy
    redirect_to matters_url, notice: '案件を削除しました！'
  end

  private

  def set_matter
    @matter = Matter.find(params[:id])
  end

  def matter_params
    params.require(:matter).permit(:content, :latitude, :longitude, :status, :priority, :start_time, :end_time, :remark, :mail_status, :send_email, images: [], label_ids: [])
  end

  def user_confirmation
    redirect_to root_path unless @matter.user_id == current_user.id || current_user.admin?
  end
end

app/helpers/admin/matters_helper.rb
module Admin::MattersHelper
end

app/views/matters/_form.html.erb
  <%= form_with(model: matter, local: true) do |form| %>
    <% if matter.errors.any? %>
    <div class="container">
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <ul>
        <% matter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>

<div class="container bg-color form p-2 rounded">
  <form>
    <div class="form-row">
      <div class="form-group col-md-10">
        <%= form.label :content, class:"font-weight-bold" %>　<span class="badge badge-danger">必須</span>
        <%= form.text_area :content, class: 'form-control', placeholder: "要望内容を書いてください" %>
      </div>
    </div>

    <p>※該当項目にチェックを付けてください　<span class="badge badge-secondary">任意</span></p>
    <div class="form-row">
      <div class="form-group col-md-10">
        <%= form.collection_check_boxes :label_ids, Label.all, :id, :name do |b| %>
          <div class="form-check-inline">
            <strong><%= b.check_box + b.label { b.text } %></strong>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :images, class:"font-weight-bold" %>　<span class="badge badge-secondary">任意</span>
      <div id="file" class="input-group">
        <div class="custom-file">
          <%= form.file_field :images, multiple: true, id: "customfile" , class: 'custom-file-input' %>
          <label class="custom-file-label" for="customfile" data-browse="参照">ファイル選択...</label>
        </div>
        <div class="input-group-append">
            <button type="button" class="btn btn-outline-secondary reset">取消</button>
        </div>
      </div>
      <p>※複数の写真を添付できます！</p>
    </div>

    <script>
      $('.custom-file-input').on('change', handleFileSelect);
function handleFileSelect(evt) {
        $('#preview').remove();// 繰り返し実行時の処理
        $(this).parents('.input-group').after('<div id="preview"></div>');

    var files = evt.target.files;

    for (var i = 0, f; f = files[i]; i++) {

        var reader = new FileReader();

        reader.onload = (function(theFile) {
            return function(e) {
                if (theFile.type.match('image.*')) {
                    var $html = ['<div class="d-inline-block mr-1 mt-1"><img class="img-thumbnail" src="', e.target.result,'" title="', escape(theFile.name), '" style="height:100px;" /><div class="small text-color text-center">', escape(theFile.name),'</div></div>'].join('');// 画像では画像のプレビューとファイル名の表示
                } else {
                    var $html = ['<div class="d-inline-block mr-1"><span class="small">', escape(theFile.name),'</span></div>'].join('');//画像以外はファイル名のみの表示
                }

                $('#preview').append($html);
            };
        })(f);

        reader.readAsDataURL(f);
    }
    $(this).next('.custom-file-label').html(+ files.length + '個のファイルを選択しました');
}

//ファイルの取消
$('.reset').click(function(){
    $(this).parent().prev().children('.custom-file-label').html('ファイル選択...');
    $('#preview').remove();
    $('.custom-file-input').val('');
})
    </script>

    <div class="form-row">
      <div class="form-group col-md-2">
        <%= form.label :priority, class:"font-weight-bold" %>　<span class="badge badge-secondary">任意</span>
        <%= form.select :priority, [:高, :中, :低 ], {}, { class: 'form-control' }  %>
      </div>
    </div>
    <p class="m-0">参考：</p>
    <p class="m-0">高：今日中にやって欲しい。</p>
    <p class="m-0">中：１週間以内にやって欲しい。</p>
    <p class="m-0">低：１ヶ月以内にやって欲しい。</p>

    <p class="font-weight-bold mt-3">場所</p>
    <p>※マーカーをドラッグして該当箇所に落としてください</p>
    <div class="form-row">
      <div id="map"></div><!-- 地図を表示する div 要素（id="map"）-->
    </div>

    <div class="form-row mt-1">
      <div class="form-group col-md-3">
        <%= form.text_field :latitude, id: "target_latitude", class: 'form-control', placeholder: "緯度" %>
      </div>

      <div class="form-group col-md-3">
        <%= form.text_field :longitude, id: "target_longitude", class: 'form-control', placeholder: "経度" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-10">
        <%= form.label :remark, class:"font-weight-bold" %>
        <%= form.text_area :remark, class: 'form-control', placeholder: "気軽にお書きください！" %>
      </div>
    </div>

    <% if current_user.admin? %>
    <p>--以下は管理者のみ記入可能です。--</p>
      <div class="form-row">
        <div class="form-group col-md-3">
          <%= form.label :status, class:"font-weight-bold" %>
          <%= form.select :status, [["未着手"],["工事中"],["工事完了"]], { include_blank: "選択してください" }, { class: 'form-control' } %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-2">
          <%= matter.mail_status %>
        </div>
        <div class="form-group col-5">
          <%= form.check_box :send_email ,{}, "true", "false" %>
          <%= form.label '工事完了メールを送信する' %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <%= form.label :start_time, class:"font-weight-bold" %>
          <%= form.date_field :start_time, class: 'form-control' %>
        </div>

        <div class="form-group col-md-4">
          <%= form.label :end_time, class:"font-weight-bold" %>
          <%= form.date_field :end_time, class: 'form-control' %>
        </div>
      </div>
    <% end %>
      <div class="actions">
        <%= form.submit '登録する',  class: 'btn btn-primary' %>
      </div>
  <% end %>
  <style>
  /* マップを表示する div 要素の高さを必ず明示的に指定します。 */
  #map {
    height: 400px;
    width: 600px;
  }
  </style>
  </form>
</div>


<script>
  var map;
  // 現在地取得処理

      function initMap() {
        // Geolocation APIに対応している
        if (navigator.geolocation) {
          // 現在地を取得
          navigator.geolocation.getCurrentPosition(
            // 取得成功した場合
            function(position) {
              // 緯度・経度を変数に格納
              var latitude = position.coords.latitude
              var longitude = position.coords.longitude
              var mapLatLng = new google.maps.LatLng(latitude, longitude);
              // マップオプションを変数に格納
              var mapOptions = {
                zoom : 15,          // 拡大倍率
                center : mapLatLng  // 緯度・経度
              };
              // マップオブジェクト作成
              var map = new google.maps.Map(
                document.getElementById("map"), // マップを表示する要素
                mapOptions         // マップオプション
              );
              //　マップにマーカーを表示する
              var marker = new google.maps.Marker({
                map : map,
                draggable: true,            // 対象の地図オブジェクト
                position : mapLatLng   // 緯度・経度
              });
              //マーカーのドロップ（ドラッグ終了）時のイベント
              google.maps.event.addListener(marker, 'dragend', function(e) {
                //イベントの引数eの、プロパティ.latLngがmarkerの緯度経度。
                document.getElementById( "target_latitude" ).value = e.latLng.lat(),
                document.getElementById( "target_longitude" ).value = e.latLng.lng()
              });
            },
            // 取得失敗した場合
            function(error) {
              // エラーメッセージを表示
              switch(error.code) {
                case 1: // PERMISSION_DENIED
                  alert("位置情報の利用が許可されていません");
                  var mapLatLng = new google.maps.LatLng(35.681236, 139.767125);
                  // マップオプションを変数に格納
                  var mapOptions = {
                    zoom : 15,          // 拡大倍率
                    center : mapLatLng  // 緯度・経度
                  };
                  // マップオブジェクト作成
                  var map = new google.maps.Map(
                    document.getElementById("map"), // マップを表示する要素
                    mapOptions         // マップオプション
                  );
                  //　マップにマーカーを表示する
                  var marker = new google.maps.Marker({
                    map : map,
                    draggable: true,            // 対象の地図オブジェクト
                    position : mapLatLng   // 緯度・経度
                  });
                  //マーカーのドロップ（ドラッグ終了）時のイベント
                  google.maps.event.addListener(marker, 'dragend', function(e) {
                    //イベントの引数eの、プロパティ.latLngがmarkerの緯度経度。
                    document.getElementById( "target_latitude" ).value = e.latLng.lat(),
                    document.getElementById( "target_longitude" ).value = e.latLng.lng()
                  });
                  break;
                case 2: // POSITION_UNAVAILABLE
                  alert("現在位置が取得できませんでした");
                  break;
                case 3: // TIMEOUT
                  alert("タイムアウトになりました");
                  break;
                default:
                  alert("その他のエラー(エラーコード:"+error.code+")");
                  break;
              }
            }
          );
        // Geolocation APIに対応していない
        } else {
          alert("この端末では位置情報が取得できません");
          var mapLatLng = new google.maps.LatLng(35.681236, 139.767125);
          // マップオプションを変数に格納
          var mapOptions = {
            zoom : 15,          // 拡大倍率
            center : mapLatLng  // 緯度・経度
          };
          // マップオブジェクト作成
          var map = new google.maps.Map(
            document.getElementById("map"), // マップを表示する要素
            mapOptions         // マップオプション
          );
          //　マップにマーカーを表示する
          var marker = new google.maps.Marker({
            map : map,
            draggable: true,            // 対象の地図オブジェクト
            position : mapLatLng   // 緯度・経度
          });
          //マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener(marker, 'dragend', function(e) {
            //イベントの引数eの、プロパティ.latLngがmarkerの緯度経度。
            document.getElementById( "target_latitude" ).value = e.latLng.lat(),
            document.getElementById( "target_longitude" ).value = e.latLng.lng()
          });
        }
      }
google.maps.event.addDomListener(window, 'load', initMap);
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['APIKEY']%>&callback=initMap" async defer></script>

app/views/matters/edit.html.erb
<div class="container">
  <div class="row my-3">
    <h2>案件編集</h2>
  </div>
</div>


<%= render 'form', matter: @matter %>

app/views/matters/index.html.erb
<div class="container mt-3">
  <h3 class="map text-center">案件箇所マップ</h3>
  <p class="map text-center">※<span class="text-warning">未着手(黄色)</span>、<span class="text-danger">工事中(赤)</span>のみマッピングしています。</p>
  <div class="row">
      <div id="map" class="map"></div>
  </div>
  <div class="row">

  </div>

    <h2 class="mt-3">お知らせ
      <% if current_user.admin? %>
        <button class="btn btn-secondary float-right information" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          <i class="fas fa-plus"></i>
        </button>
      <% end %>
    </h2>

  <div class="row rounded p-2" id = "information">
    <div id="informations_area">
        <%= render partial: 'informations/index', locals: { informations: @informations } %>
    </div>
  </div>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <%= render partial: 'informations/form', locals: { information: @information } if current_user.admin?%>
    </div>
  </div>



  <div class="row">
    <div class="col-12 m-2">
      <%= link_to new_matter_path do %>
        <button type="button" class="btn btn-primary float-right" id="new"><i class="fas fa-plus-circle"></i>新規案件</button>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 bg-color index  pt-3">
      <%= render 'matter_search', search: @search %>
    </div>
    <div class="col-md-9 bg-color index pt-3">
      <table width="100%" >
        <thead>
          <tr>
            <th width="10%"></th>
            <th width="30%" class="text-center">要望内容</th>
            <th width="10%" class="text-center">進捗状況</th>
            <th width="15%" class="text-center"><%= sort_link(@search, :priority, '優先順位') %></th>
            <th width="15%" class="text-center"><%= sort_link(@search, :created_at, '作成日時') %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @matters.each do |matter| %>
            <% if matter.status == "未着手" %>
              <tr class="matter bg-warning">
            <% elsif matter.status =="工事中" %>
              <tr class="matter bg-danger">
            <% else %>
              <tr class="matter bg-secondary">
            <% end %>
                <td width="7%"><%= image_tag set_image(matter.user.icon, 'default.png'), class: 'icon mx-auto', size: '48x48' %></td>
                <td width="34%"><%= matter.content.truncate(18) %></td>
                <td width="10%" class="text-center"><%= matter.status %></td>
                <td id='priority_row' width="10%" class="text-center" ><%= matter.priority %></td>
                <td width="15%" class="text-center"><%= matter.created_at.strftime('%Y/%m/%d') %></td>
                <td width="2%"><i class="fas fa-thumbs-up fa-2x"></i></td>
                <td width="2%"><%= matter.favorites.count %></td>
                <td width="2%">
                  <%= link_to matter do%>
                    <i class="fas fa-file-alt fa-2x"></i>
                    <% end %>
                </td>
                <% if (matter.user_id == current_user.id) || (current_user.admin == true) %>
                  <% if (matter.latest_sender != current_user.name) && (matter.latest_sender != nil) %>
                    <td width="3%" class="bg-color"><i class="far fa-envelope fa-2x"></i></td>
                  <% end %>
                <% else %>
                    <td width="3%" class="bg-color"></td>
                <% end %>
              </tr>
          <% end %>
          <%= paginate @matters %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<style>
/* マップを表示する div 要素の高さを必ず明示的に指定します。 */
#map {
  height: 400px;
  width: 900px;
}
</style>
<body>
<!-- 地図を表示する div 要素（id="map"）-->
<script>
  var map;
function initMap() {
  var myLatlng = new google.maps.LatLng(35.893867,139.633587);
 //インスタンスを作成
 map = new google.maps.Map(document.getElementById('map'), {
  //地図のオプション
  //初期のズームレベル
  zoom: 7,
  //地図の中心点
  center: myLatlng
 });
 //マーカーの初期プロパティを指定
 <% @matters.each do |matter| %>
  <% if matter.latitude.present? && matter.status != "工事完了" %>
      (function(){
        var contentString = '<%= link_to matter.content.truncate(8), matter  %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:{lat: <%= matter.latitude %>, lng: <%= matter.longitude %>},
            map: map,
            title: contentString,
            <% if matter.status == '未着手' %>
              icon: "https://maps.google.com/mapfiles/ms/micons/yellow-dot.png"
            <% else %>
              icon: "https://maps.google.com/mapfiles/ms/micons/red-dot.png"
            <% end %>
        });

        infowindow.open(map, marker);

        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
       })();
    <% end %>
  <% end %>
}
google.maps.event.addDomListener(window, 'load', initMap);
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['APIKEY']%>&callback=initMap" async defer></script>

app/views/matters/new.html.erb
<div class="container">
  <div class="row my-3">
    <h2>新規案件</h2>
  </div>
</div>

<%= render 'form', matter: @matter %>

app/views/matters/show.html.erb
<div class="container mt-3">
  <div class="row m-0">
    <h2>案件詳細</h2>
    <div class="ml-auto ">
      <% if current_user == @matter.user || current_user.admin? %>
        <%= link_to edit_matter_path(@matter) do %>
          <i class="fas fa-edit fa-2x"></i>
        <% end %>
        <%= link_to @matter, method: :delete, data: { confirm: '本当に削除しますか？' } do %>
          <i class="fas fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="container mt-3 form p-2 rounded">
  <div class="row m-0 py-4 show m-0 py-4">
    <div class="col-md-10">
      <h5 class="font-weight-bold">要望内容</h5>
      <p><%= @matter.content %></p>
      <h5>
        <% if @matter.labels %>
          <p>
            <% @matter.labels.each do |label| %>
              <span class="badge badge-info" ><%= label.name %></span>
            <% end %>
          </p>
        <% end %>
      </h5>
    </div>
  </div>

  <div class="row m-0 py-4 show m-0 py-4">
    <div class="col-md-12">
      <h5 class="font-weight-bold">写真ファイル</h5>
      <% if @matter.images.attached? %>
        <% @matter.images.each do |image| %>
          <%=  link_to image, 'data-lightbox': image do %>
            <%= image_tag image.variant(resize:'100x100').processed  %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-12">
      <% if @matter.images.present? %>
        <p>※クリックしたら拡大できます。</p>
      <% end %>
    </div>
  </div>

  <br>

  <div class="row m-0 py-4 show">
    <div class="col-md-3">
      <h5 class="font-weight-bold">進捗状況:
        <% if @matter.status == "未着手" %>
          <span class="badge badge-warning"><%= @matter.status %></span>
        <% elsif @matter.status == "工事中" %>
          <span class="badge badge-danger"><%= @matter.status %></span>
        <% else %>
          <span class="badge badge-secondary"><%= @matter.status %></span>
        <% end %>
        </h5>

    </div>

    <div class="col-md-3">
        <h5 class="font-weight-bold">緊急度:<span><%= @matter.priority %></span></h5>
    </div>
  </div>

  <% if @matter.latitude.present? %>
    <div class="row m-0 py-4">
      <div class="col-md-3">
        <h5 class="font-weight-bold">場所</h5>
      </div>
    </div>
    <div class="row m-0">
      <div id="map"></div>
    </div>
    <div class="row m-0 py-4 show">
      <div class="col-md-4">
        <p>緯度:<%= @matter.latitude %></p>
      </div>

      <div class="col-md-4">
        <p>経度:<%= @matter.longitude %></p>
      </div>
    </div>
  <% end %>

  <% if @matter.remark? %>
    <div class="row m-0 py-4 show">
      <div class="col-md-10">
        <h5 class="font-weight-bold">備考</h5>
        <p><%= @matter.remark %></p>
      </div>
    </div>
  <% end %>

  <% if current_user.admin? %>
  <p>※以下は管理者のみ表示されます</p>
    <div class="row m-0">
      <div class="col-md-3">
        <h5 class="font-weight-bold">工事完了メール</h5>
      </div>
    </div>
    <div class="row m-0 py-4 show">
      <div class="col-md-4">
        <h5>
          <% if @matter.mail_status == "未送信" %>
            <span class="badge badge-warning"><%= @matter.mail_status %></span>
          <% else %>
            <span class="badge badge-secondary"><%= @matter.mail_status %></span>
          <% end %>
        </h5>
      </div>

      <div class="col-md-4">
        <p class="font-weight-bold"><%= "完了メール送信予定" if @matter.send_email %></p>
      </div>
    </div>

    <% if @matter.start_time? %>
      <div class="row m-0 py-4 show">
        <div class="col-md-4">
          <h5 class="font-weight-bold">工事開始日</h5>
          <p><%= @matter.start_time.strftime('%Y/%m/%d') %></p>
        </div>
    <% end %>
    <% if @matter.end_time? %>
        <div class="col-md-3">
          <h5 class="font-weight-bold">工事終了日</h5>
          <p><%= @matter.end_time.strftime('%Y/%m/%d') %></p>
        </div>
      </div>
    <% end %>

  <% end %>

  <p>
    <span>
      <div id="favorites_buttons_<%= @matter.id %>">
        <%= render partial: 'favorites/favorite', locals: { matter: @matter} %>
      </div>
    </span>
    <span>
      <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <i class="fas fa-comments"></i>
      </button>
    </span>
  </p>

  <div class="collapse " id="collapseExample">
    <div class="card card-body">
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, matter: @matter } %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, matter: @matter } %>
    </div>
  </div>

</div>
<style>
#map {
  height: 400px;
  width: 600px;
}
</style>


<script>
  var map;
function initMap() {
  var latitude = <%= @matter.latitude %>
  console.log(latitude);
  var longitude = <%= @matter.longitude %>
  var myLatlng = new google.maps.LatLng(latitude, longitude);
 map = new google.maps.Map(document.getElementById('map'), {
  zoom: 12,
  //地図の中心点
  center: myLatlng
 });
 marker = new google.maps.Marker({
  position: myLatlng,
  draggable: false,
  map: map,
 });
}
google.maps.event.addDomListener(window, 'load', initMap);
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['APIKEY']%>&callback=initMap" async defer></script>