config/routes.rb
Rails.application.routes.draw do
  root to: 'other_pages#index'

  get 'users/show' => 'users#show'

  resources :matters do
    resources :comments
    resource :favorites, only: %i[create destroy]
  end

  resources :informations, only: %i[create edit update destroy]

  resources :notifications, only: :index

  resources :conversations do
    resources :messages
  end

  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :matters, only: %i[index show edit update destroy]
    resources :labels
  end

  # ゲストユーザー機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }

  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < ApplicationController
  def create
    @label = Label.new(label_params)
    respond_to do |format|
      if @label.save
        @labels = Label.all
        format.js { render :index }
      else
        format.html { redirect_to matters_path, alert: '投稿できませんでした...' }
      end
    end
  end

  # DELETE /labels/1
  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      @labels = Label.all.order(created_at: :desc)
      format.js { render :index }
    end
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/admin/labels/_form.html.erb
  <%= form_with model: label, url: admin_labels_path  do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>
      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-2">
      <%= form.label :name %>
      <%= form.text_field :name, {class: 'form-control', id: 'label_form'}  %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit '登録する',  class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/labels/_index.html.erb
<% labels.each do |label| %>
  <% if label.id.present? %>
    <div class="label-content" id ="this_label_<%= label.id %>">
      <h4><span class="badge badge-info"><%= label.name %></span>
        <span>
          <%= link_to admin_label_path(label), method: :delete, remote: true, data: { confirm: "本当に削除しますか?"} do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </span>
      </h4>
    </div>
  <% end %>
<% end %>

app/views/admin/labels/destroy.js.erb
$('#label_<%= @label.id %>').remove();

app/views/admin/labels/index.js.erb
$("#labels_area").html("<%= j(render 'admin/labels/index', { labels: @labels }) %>")
$("#label_form").val('')