config/routes.rb
Rails.application.routes.draw do
  root to: 'other_pages#index'

  get 'users/show' => 'users#show'

  resources :matters do
    resources :comments
    resource :favorites, only: %i[create destroy]
  end

  resources :informations, only: %i[create edit update destroy]

  resources :notifications, only: :index

  resources :conversations do
    resources :messages
  end

  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :matters, only: %i[index show edit update destroy]
    resources :labels
  end

  # ゲストユーザー機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/information.rb
class Information < ApplicationRecord
  validates :content, presence: true
  scope :latest, -> {all.order(created_at: :asc)}
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :set_information, only: %i[edit update destroy]
  before_action :authenticate_user!

  def create
    @information = Information.new(information_params)
    respond_to do |format|
      if @information.save
        @informations = Information.all
        format.js { render :index }
      else
        format.html { redirect_to matters_path, alert: '投稿できませんでした...' }
      end
    end
  end

  def edit
    respond_to do |format|
      flash.now[:notice] = 'お知らせの編集中'
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @information.update(information_params)
        @informations = Information.latest
        flash.now[:notice] = 'お知らせが編集されました'
        format.js { render :index }
      else
        flash.now[:alert] = 'お知らせの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @information.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      @informations = Information.latest
      format.js { render :index }
    end
  end

  private

  def set_information
    @information = Information.find(params[:id])
  end

  def information_params
    params.require(:information).permit(:content)
  end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/_edit.html.erb
<%= form_with model: information do |form| %>
  <% if information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>
      <ul>
      <% information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group">
      <h5><span class="badge badge-warning">変更中</span></h5>
      <%= form.text_area :content, class: 'form-control'  %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit '変更する', class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/informations/_form.html.erb
  <%= form_with model: information, url: informations_path  do |form| %>
  <% if information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>
      <ul>
      <% information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label 'お知らせを追加する' %>
      <%= form.text_area :content, class: 'form-control'  %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit '追加する', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/informations/_index.html.erb
<p>勤務時間は平日の8時半〜１７時までです。</p>
<% informations.each do |information| %>
  <% if information.id.present? %>
    <div class="information-content" id ="this_information_<%= information.id %>"></div>
      <p>
      <%= information.content %>
      <% if current_user.admin? %>
        <span>
          <%= link_to edit_information_path(information), remote: true do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </span>
        <span>
          <%= link_to information_path(information), method: :delete, remote: true, data: { confirm: "本当に削除しますか?"} do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </span>
      </p>
      <% end %>
  <% end %>
<% end %>

app/views/informations/destroy.js.erb
$('#information_<%= @information.id %>').remove();

app/views/informations/edit.js.erb
$("#this_information_<%= @information.id %>").replaceWith("<%= j render 'informations/edit', information: @information %>");

app/views/informations/index.js.erb
$("#informations_area").html("<%= j(render 'informations/index', { informations: @informations }) %>")
$("textarea").val('')

app/views/informations/update.js.erb
$('#informations_area').replaceWith
("<%=j render 'informations/index', information: @information, informations: @informations, remote: true %>");