config/routes.rb
Rails.application.routes.draw do
  root to: 'other_pages#index'

  get 'users/show' => 'users#show'

  resources :matters do
    resources :comments
    resource :favorites, only: %i[create destroy]
  end

  resources :informations, only: %i[create edit update destroy]

  resources :notifications, only: :index

  resources :conversations do
    resources :messages
  end

  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :matters, only: %i[index show edit update destroy]
    resources :labels
  end

  # ゲストユーザー機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :phone_number, format: {with: /\A\d{10,11}\z/}
  # 管理者がいなくならないようにコールバック
  before_destroy :check_destroy
  # 画像アップロード
  has_one_attached :icon

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :matters, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # user編集時にcurrent_passwordを入れないようにする処理関係
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(name: 'ゲスト(管理者)', email: 'guest@example.com', admin: true) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  private

  def check_destroy
    throw :abort if User.where(admin: true).count == 1 && admin == true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: %i[show edit update destroy]
  before_action :check_guest, only: %i[update destroy]


  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "#{@user.name}を編集しました。"
    else
      flash[:alert] = '編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "#{@user.name}を削除しました。"
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :user_image, :phone_number, :user_place, :remark, :icon, :admin)
  end

  def check_guest
    if @user.email == 'guest@example.com'
      redirect_to admin_users_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。' if params[:user][:email].downcase == 'guest@example.com'
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :authenticate_user!
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    redirect_to matters_path, alert: 'ゲストユーザーの変更・削除はできません。' if resource.email == 'guest@example.com'
  end

  def after_sign_up_path_for(_resource)
    matters_path
  end

  # アカウント編集後のリダイレクト先
  def after_update_path_for(_resource)
    users_show_path
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to matters_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_with(model: @user, url: admin_user_url(@user), local: true) do |form| %>
  <% if @user.errors.any? %>
    <div class="container">
      <div id="error_explanation"class="alert alert-danger" role="alert">
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div class="container mt-5 bg-color form p-2 rounded">
  <div class="row">
    <div class="col-md-8 mx-auto">
        <%= image_tag set_image(@user.icon, 'default.png'), class: 'icon' , id: :img_prev , size: '90x90' %>
        <div class="form-group">
          <%= form.label 'ユーザーアイコン' %> <br />
          <%= form.file_field :icon, id: :icon %>
        </div>

        <script type="text/javascript">
          $(function() {
           function readURL(input) {
             if (input.files && input.files[0]) {
               var reader = new FileReader();
               reader.onload = function (e) {
                 $('#img_prev').attr('src', e.target.result);
               }
               reader.readAsDataURL(input.files[0]);
             }
           }
           $("#icon").change(function(){
             readURL(this);
           });
          });
        </script>

        <div class="field form-group">
          <%= form.label :name %>　<span class="badge badge-danger">必須</span>
          <%= form.text_field :name, class: 'form-control', id: 'user' %>
        </div>

        <div class="field form-group">
          <%= form.label :email %>　<span class="badge badge-danger">必須</span>
          <%= form.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label '電話番号' %>　<span class="badge badge-secondary">任意</span>
          <%= form.text_field :phone_number, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= form.label :user_place %>　<span class="badge badge-secondary">任意</span>
          <%= form.text_field :user_place, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= form.label :remark %>　<span class="badge badge-secondary">任意</span>
          <%= form.text_area :remark, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= form.check_box :admin ,{}, "true", "false" %>
          <%= form.label '管理者登録' %>
        </div>

        <div class="actions">
          <%= form.submit '更新する', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
  <div class="container mt-5">
    <div class="row mx-a">
      <% @users.each do |user| %>
        <div class="card col-lg-4 m-3 p-0" style="max-width: 15rem;" >
          <div class="card-header bg-color p-0 border border-top-0">
            ユーザー情報
            <span class="float-right">
              <%= link_to admin_user_path(user.id), method: :delete, data: { confirm: '削除してもよろしいですか?' } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </span>
            <span class="float-right">
              <%= link_to edit_admin_user_path(user.id) do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </span>
            <span class="float-right">
              <%= link_to admin_user_path(user.id) do %>
                <i class="fas fa-file-alt"></i>
              <% end %>
            </span>
          </div>
          <%= image_tag set_image(user.icon, 'default.png'), class: 'icon mx-auto', size: '90x90' %>
          <div class="card-body mx-auto">
            <h4 class="card-title"><%= user.name %></h4>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= render 'user_show', user: @user, edit_path: edit_admin_user_path(@user.id)  %>